name: conan-package-resources-and-notify

on:
  push:
    paths:
      - '.github/workflows/conan-package-resources.yml'
      - 'resources/definitions/**'
      - 'resources/extruders/**'
      - 'resources/images/**'
      - 'resources/intent/**'
      - 'resources/meshes/**'
      - 'resources/quality/**'
      - 'resources/variants/**'
      - 'resources/conanfile.py'
    branches:
      - 'main'
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
  get-conan-recipe-version:
    uses: ./.github/workflows/get-conan-recipe-version.yml
    with:
      conan_recipe_root: "./resources/"
      repository: ${{ github.repository }}
      branch: ${{ github.ref_name }}
      release: false
      internal: false
    secrets: inherit

  conan-package:
    name: Create Conan Package
    needs: get-conan-recipe-version
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@main
    with:
      conan_recipe_root: "./resources/"
      platform_windows: false
      platform_mac: false
      install_system_dependencies: false
    secrets: inherit

  notify-dependent-package:
    name: Notify Dependent Repository
    needs: [get-conan-recipe-version, conan-package]
    runs-on: ubuntu-latest

    steps:
      - name: Notify Dependent Repository
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDENT_REPO_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/DEPENDENT_ORG/DEPENDENT_REPO/dispatches \
          -d '{"event_type": "dependency-version-update", "client_payload": { "version": "${{ needs.get-conan-recipe-version.outputs.version_base }}", "full_version": "${{ needs.get-conan-recipe-version.outputs.version_full }}", "package_name": "${{ needs.get-conan-recipe-version.outputs.package_name }}" }}'